### PR TITLE
configure pipeline

### PR DESCRIPTION
**Pull request by drewbo**
## Changes proposed in this pull request:
- use the new init task to configure the pipeline

## Security considerations
None

### CODE REVIEW

**Review by svenaas — CHANGES_REQUESTED** [review]
Did you mean to add `src/set-pipeline.yml` to this branch?

**Comment by drewbo** [comment]
@svenaas Nope. I'm still working up the documentation but this was the "compiled" pipeline I talked about in eng meeting/scrum: https://github.com/cloud-gov/pages-pipeline-tasks/blob/main/scripts/init.sh

**Comment by svenaas** [comment]
OK, that's cool. But it doesn't look like `set-pipeline` has been tried with the version on this branch yet. Is that worth doing before this merges?

**Comment by drewbo** [comment]
https://github.com/cloud-gov/pages-mailer/pull/43/commits/bc036d6526882f2454e9c3ee6c58d53e43bb7944 does produce the file at `src/set-pipeline.yml` but the `set_pipeline` step still complains it isn't there, I might revert to the prior commit even though it looks more confusing cc: @svenaas @apburnes

**Comment by apburnes** [comment]
> [bc036d6](https://github.com/cloud-gov/pages-mailer/commit/bc036d6526882f2454e9c3ee6c58d53e43bb7944) does produce the file at `src/set-pipeline.yml` but the `set_pipeline` step still complains it isn't there, I might revert to the prior commit even though it looks more confusing cc: @svenaas @apburnes

Was the prior commit using a separate task for the init pipeline with a `put` action before running the `set_pipeline`?

**Comment by drewbo** [comment]
No, it added it to the src artifact folder, no `put` step, and it was available for the `set_pipeline` step in the next job (I think)

**Review by svenaas — APPROVED** [review]

**Pull request merged**
